### ISSUE TITLE
怎么实现把终端传过来的视频流输入ffmpeg呢？

### ISSUE THREAD

**Issue by ldming-com** [SmallChi/JT1078DotNetty#2]
SimpleServer示例中对ffmpeg -i 好像是用的本地摄像头模拟的，怎么把收到的终端的视频流输入到ffmpeg呢？

**Comment by SmallChi** [comment]
不好意思，实际终端上来的数据，是通过自己手动解码，封装视频格式，不借助ffmpeg。倘若想要用ffmpeg也可以，通过子进程的方式(命名管道)将数据发给ffmpeg进行解码封装。

**Comment by ldming-com** [comment]
@SmallChi 方便加个QQ吗，目前也在搞这一块，.net这方面的资料好少

**Comment by SmallChi** [comment]
564952747

**Comment by ldming-com** [comment]
加了
