### ISSUE TITLE
flv最新的6版本 dll会错误

### ISSUE THREAD

**Issue by Crowsflying** [SmallChi/JT1078DotNetty#4]
TJ1078.Flv 找不到这个dll包 

![image](https://user-images.githubusercontent.com/58463152/90307919-8bb9cd00-df0d-11ea-8622-57c5960023b4.png)

![image](https://user-images.githubusercontent.com/58463152/90307876-38e01580-df0d-11ea-9075-d443d7e18dbb.png)

**Comment by Crowsflying** [comment]
![3NX@% A K99KESO~K4XG AO](https://user-images.githubusercontent.com/58463152/90307940-d9363a00-df0d-11ea-9040-4830dc437c2e.png)

**Comment by Crowsflying** [comment]
安装 6版本 
FlvEncoder encoder = new FlvEncoder(); 就会报错

**Comment by SmallChi** [comment]
应该是有个大兄弟把音频库加上去以后，没有调式到位，下周看看。
