### ISSUE TITLE
如何完整的实现流程。

### ISSUE THREAD

**Issue by 270sun** [SmallChi/JT1078DotNetty#6]
你好，我最近正在研究学习这个代码。有一些疑问。还请帮忙解答一下。如何搭建这些服务，并打通整个流程。

使用Kafka队列，用的**不是DotNetty**
目标流程：
1. 设备可以上报位置信息。（808）
2. 通过客户端对设备下发推流指令
3. 在网页上实时观看设备推流的信息。

我当前是这么理解的：
0. 用Simple Client来给设备下发指令。（目前有一个1078的设备）
1.用808Gateway Simple (QueueNotification/QueueServer/QueueService) 来接受消息
2. 在800Gateway SimpleQueueService中添加了1078扩展，添加了对例如0x9010 实时音视频传输请求 指令的处理，当前处理方式是直接返回原始数据 request.OriginData.ToArray() (byte[])
3. 用JT1078 Gateway 来接受视频服务。
4. 用代码中的index.html + flv.js 来观看实时视屏流。

但是整个流程一直调试不通，不知道上面的理解和环境的搭建是否有问题？
如果方便的话，是否可以我们线下交流一下，谢谢！

**Comment by SmallChi** [comment]
跟您描述差不多是这样的，先有808，然后设备连接上以后，下发0x9010,连接上推流，web用httpflv或者wsflv进行连接观看。

**Comment by 270sun** [comment]
现在遇到的还有一个问题是，我从tcp client发了一个视频推流的指令，但是貌似指令一直没有发到设备上，而是返回到了tcp client 上。我在发送的指令里面的Header里面写了设备的sim卡号，但是貌似没有推过去。不知道是哪里的问题

**Comment by SmallChi** [comment]
应该是姿势不对😅
