### ISSUE TITLE
最新情况

### ISSUE THREAD

**Issue by ldming-com** [SmallChi/JT1078DotNetty#7]
1. 音频转码可用 EasyAccEncoder.Net ，目前已在实际应用中完成G711A到AAC的转换，并成功实现使用flv.js播放。其它，G711U、G726、PCM到AAC未测试，应该也可转换。
2. HttpListener 作为flv流服务器，有个需要注意的地方，一定要在写入流数据后使用OutputStream.Close() 或 Response.Close() 方法。
推荐使用方法为 JT1078HttpContextExtensions.cs 中 HttpM3U8Async() 这种使用传入 Stream ，内部使用 await stream.CopyToAsync(context.Response.OutputStream，用Stream来阻塞http连接结束。

像 HttpSendFirstChunked()/HttpSendChunked() 这种，传入byte[]使用 Write()写入数据，在未使用Close()的情况下，就算使用 Flush 也无效，会导致发送到客户端的数据将非常缓慢。
 
具体表现就是，前端使用flv.js或VLC播放flv流时首屏展现时间基本都在10-20s以上，并且随着播放时间越长，延迟越严重，导致视频卡顿，服务器上堆积大量待发送到客户端消息。
 
关于 HttpListener  OutputStream 使用 Write()写入数据后，Flush无效相关链接
https://stackoverflow.com/questions/794207/how-to-flush-httplistener-response-stream
https://stackoverflow.com/questions/5231291/httplistener-response-flushes-to-soon-for-large-buffers
https://stackoverflow.com/questions/13385633/serving-large-files-with-c-sharp-httplistener
https://stackoverflow.com/questions/794207/how-to-flush-httplistener-response-stream/794417#794417

**Comment by SmallChi** [comment]
HttpListener确实不好用，新版会用Kestrel。

**Comment by ldming-com** [comment]
新版在那儿？

**Comment by ldming-com** [comment]
更正一下，关于HttpListener  OutputStream 输出数据很慢的情况：

与后面有没有使用 Close() 关闭流无关，与 Flush 也没有关系（Flush 无效）。
影响发送速度的关键在于，是发送数据包的大小。

用以下测试代码，发现如果每次发送的数据包大小都不一致，则客户端下载速度只有 500Kb/s ，最好的的情况 700多。
如果将发送缓冲区设置为 1024、4096 之类的，可以达到5Mb/s 左右。

使用 stream.CopyToAsync(context.Response.OutputStream) 效率最好，可以达到8Mb/s左右。


这个测试不严谨的地方在于，File.OpenRead 是一个稳定的数据源，能否可以利用 stream.CopyToAsync(context.Response.OutputStream)  使用 stream.Flush 达到刷新 OutputStream 的目的还待继续测试。
 

```

        private async void ProcessTest(HttpListenerContext context)
        {
            try
            {
                context.Response.AddHeader("Access-Control-Allow-Headers", "*");
                context.Response.AppendHeader("Access-Control-Allow-Origin", "*");


                var path = Path.Combine(Environment.CurrentDirectory, "wwwroot");

                if (Directory.Exists(path))
                {
                    var files = Directory.GetFiles(path, "*.zip");
                    if (files.Length > 0)
                    {
                        var fileName = "abc.zip";
                        context.Response.Headers.Add("Content-Disposition", $"attachment; filename=\"{fileName}\"");
                        context.Response.ContentType = "application/octet-stream";
                        context.Response.SendChunked = true;
                        using var stream =  File.OpenRead(files[0]);

                        // 模拟发送不规则大小数据包 
                        Random random = new Random();
                        int bufferLen = 128;
                        // 创建缓冲区
                        byte[] buffer = new byte[bufferLen];
                        int bytesRead;

                        // 读取文件流并写入MemoryStream
                        while ((bytesRead = stream.Read(buffer, 0, buffer.Length)) != 0)
                        {
                            bufferLen = random.Next(100, 5000);
                            buffer = new byte[bufferLen];
                            context.Response.StatusCode = (int)HttpStatusCode.OK;
                            await context.Response.OutputStream.WriteAsync(buffer);
                            await context.Response.OutputStream.FlushAsync();   
                        }

                        //context.Response.ContentLength64 = stream.Length;
                        //context.Response.KeepAlive = false;

                        //await stream.CopyToAsync(context.Response.OutputStream);



                        context.Response.OutputStream.Close();
                        context.Response.Close();
                        return;
                    }
                }

                context.Response.OutputStream.Close();
                context.Response.Close();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "出错");
            }
            await Task.CompletedTask;
        }

```
